export type MedicationGuideEntry = {
  key: string;
  names: string[];
  displayName: string;
  activeIngredient: string;
  medicationClass: string;
  defaultAction: "Manter" | "Suspender" | "Individualizar";
  timing: string;
  restart: string;
  adjustments: string;
  source: string;
  suspendDays?: number;
};

/**
 * Condutas que exigem uma orientação escrita pelo anestesiologista.
 *
 * A regra é uma só: tudo que não for "Manter" entra nas orientações finais.
 * Manter é a única conduta que não pede nada de ninguém — o paciente toma o
 * remédio como sempre tomou, e basta aparecer na lista de medicamentos em uso.
 *
 * A lista existia antes com "Suspender" e "Individualizar" apenas, e "Avaliar"
 * ficava de fora. Só que "Avaliar" é o valor com que todo medicamento nasce
 * quando o guia não o conhece, e é justamente a decisão que ainda não foi
 * tomada: era o caso que mais precisava aparecer no papel e o único que
 * sumia dele.
 */
export const CONDUTA_SEM_ORIENTACAO = "manter";

export function exigeOrientacao(conduta: string) {
  return String(conduta || "").trim().toLowerCase() !== CONDUTA_SEM_ORIENTACAO;
}

/** Mantido para leitura; a decisão real é a de `exigeOrientacao`. */
export const MEDICATION_ORIENTATION_ACTIONS = ["Suspender", "Individualizar", "Avaliar"];

const SOURCE =
  "Guia Perioperatório de Medicamentos, versão 1.0, revisão 07/2026 — SAESP 2025; Miller 7ª ed.; AHA/ACC 2024; ADA 2026; CHEST 2022; ASRA 5ª ed. 2025";

export const MEDICATION_GUIDE: MedicationGuideEntry[] = [
  {
    key: "losartana",
    names: ["losartana", "valsartana", "candesartana", "olmesartana", "telmisartana", "irbesartana", "bra"],
    displayName: "BRA (ex.: losartana)",
    activeIngredient: "Bloqueador do receptor de angiotensina",
    medicationClass: "BRA / anti-hipertensivo",
    defaultAction: "Individualizar",
    timing: "Se usado apenas para hipertensão e a cirurgia tiver risco elevado, considerar omitir cerca de 24 h antes. Em HFrEF estável, pode ser razoável manter.",
    restart: "Reiniciar assim que pressão, volemia e função renal estiverem estáveis.",
    adjustments: "Decidir conforme indicação, PA, volemia, função renal, sangramento previsto e risco de vasoplegia.",
    source: SOURCE,
  },
  {
    key: "ieca",
    names: ["enalapril", "captopril", "ramipril", "lisinopril", "perindopril", "benazepril", "ieca"],
    displayName: "IECA",
    activeIngredient: "Inibidor da enzima conversora de angiotensina",
    medicationClass: "IECA / anti-hipertensivo",
    defaultAction: "Individualizar",
    timing: "Mesma lógica dos BRA: considerar omitir cerca de 24 h antes quando usado para hipertensão em cirurgia de risco elevado.",
    restart: "Reiniciar assim que pressão, volemia e função renal estiverem estáveis.",
    adjustments: "Em insuficiência cardíaca com fração reduzida, ponderar manutenção.",
    source: SOURCE,
  },
  {
    key: "betabloqueador",
    names: ["metoprolol", "atenolol", "carvedilol", "bisoprolol", "propranolol", "nebivolol"],
    displayName: "Betabloqueador",
    activeIngredient: "Betabloqueador",
    medicationClass: "Cardiovascular",
    defaultAction: "Manter",
    timing: "Manter a dose habitual, inclusive no dia da cirurgia.",
    restart: "Manter sem interrupção; retomar assim que possível se a via oral for suspensa.",
    adjustments: "Reduzir ou omitir somente diante de bradicardia grave, choque, bloqueio avançado ou decisão cardiológica.",
    source: SOURCE,
  },
  {
    key: "aas",
    names: ["aas", "aspirina", "ácido acetilsalicílico", "acido acetilsalicilico"],
    displayName: "AAS",
    activeIngredient: "Ácido acetilsalicílico",
    medicationClass: "Antiagregante plaquetário",
    defaultAction: "Individualizar",
    timing: "A decisão depende da indicação. Em stent coronariano, manter sempre que possível. Na prevenção primária, considerar suspender 4–7 dias quando o risco hemorrágico não for trivial.",
    restart: "Manter ou reiniciar nas primeiras 24 h quando a hemostasia permitir.",
    adjustments: "Não decidir isoladamente em PCI/stent recente; considerar risco de sangramento catastrófico.",
    source: SOURCE,
  },
  {
    key: "clopidogrel",
    names: ["clopidogrel", "plavix", "iscover"],
    displayName: "Clopidogrel",
    activeIngredient: "Clopidogrel",
    medicationClass: "Antiagregante P2Y12",
    defaultAction: "Suspender",
    timing: "Quando a interrupção for aceita, suspender 5–7 dias antes.",
    restart: "Reiniciar o mais cedo possível após controle do sangramento; discutir dose de ataque com cardiologia quando indicada.",
    adjustments: "Não suspender automaticamente em stent recente. Para neuroeixo, respeitar 5–7 dias.",
    source: SOURCE,
    suspendDays: 7,
  },
  {
    key: "ticagrelor",
    names: ["ticagrelor", "brilinta"],
    displayName: "Ticagrelor",
    activeIngredient: "Ticagrelor",
    medicationClass: "Antiagregante P2Y12",
    defaultAction: "Suspender",
    timing: "Quando a interrupção for aceita, suspender 3–5 dias antes; para neuroeixo, usar 5 dias.",
    restart: "Reiniciar o mais cedo possível após controle do sangramento.",
    adjustments: "Não suspender automaticamente em stent recente.",
    source: SOURCE,
    suspendDays: 5,
  },
  {
    key: "prasugrel",
    names: ["prasugrel", "effient"],
    displayName: "Prasugrel",
    activeIngredient: "Prasugrel",
    medicationClass: "Antiagregante P2Y12",
    defaultAction: "Suspender",
    timing: "Quando a interrupção for aceita, suspender 7–10 dias antes.",
    restart: "Reiniciar o mais cedo possível após controle do sangramento.",
    adjustments: "Não suspender automaticamente em stent recente; neuroeixo exige 7–10 dias.",
    source: SOURCE,
    suspendDays: 10,
  },
  {
    key: "rivaroxabana",
    names: ["rivaroxabana", "xarelto"],
    displayName: "Rivaroxabana",
    activeIngredient: "Rivaroxabana",
    medicationClass: "DOAC (anti-Xa)",
    defaultAction: "Suspender",
    timing: "Função renal preservada: cerca de 24 h antes em baixo/moderado risco hemorrágico ou 48 h em alto risco.",
    restart: "Em geral, após cerca de 24 h em baixo/moderado risco ou 48–72 h em alto risco, somente com hemostasia segura.",
    adjustments: "Neuroeixo: dose terapêutica ≥72 h. Aumentar intervalo em insuficiência renal, baixo peso, interações ou sangramento catastrófico. Não fazer ponte rotineira.",
    source: SOURCE,
    suspendDays: 2,
  },
  {
    key: "apixabana",
    names: ["apixabana", "eliquis"],
    displayName: "Apixabana",
    activeIngredient: "Apixabana",
    medicationClass: "DOAC (anti-Xa)",
    defaultAction: "Suspender",
    timing: "Função renal preservada: cerca de 24 h antes em baixo/moderado risco hemorrágico ou 48 h em alto risco.",
    restart: "Em geral, após cerca de 24 h em baixo/moderado risco ou 48–72 h em alto risco, somente com hemostasia segura.",
    adjustments: "Neuroeixo: dose terapêutica ≥72 h. Individualizar por função renal, dose, peso e risco hemorrágico.",
    source: SOURCE,
    suspendDays: 2,
  },
  {
    key: "varfarina",
    names: ["varfarina", "marevan", "coumadin"],
    displayName: "Varfarina",
    activeIngredient: "Varfarina",
    medicationClass: "Antagonista da vitamina K",
    defaultAction: "Suspender",
    timing: "Suspender 5 dias antes e verificar INR próximo ao procedimento.",
    restart: "Em geral 12–24 h após, quando a via oral for possível e houver hemostasia.",
    adjustments: "Ponte não é rotina; reservar para risco tromboembólico muito alto. Neuroeixo exige INR normalizado.",
    source: SOURCE,
    suspendDays: 5,
  },
  {
    key: "enoxaparina",
    names: ["enoxaparina", "clexane", "versa"],
    displayName: "Enoxaparina",
    activeIngredient: "Enoxaparina",
    medicationClass: "HBPM",
    defaultAction: "Suspender",
    timing: "Dose profilática: última dose ≥12 h antes. Dose terapêutica: ≥24 h antes.",
    restart: "Individualizar pela hemostasia; após cirurgia de alto risco, dose terapêutica costuma aguardar 48–72 h.",
    adjustments: "Considerar intervalo maior na disfunção renal. Neuroeixo segue regras específicas de dose e cateter.",
    source: SOURCE,
    suspendDays: 1,
  },
  {
    key: "metformina",
    names: ["metformina", "glifage", "glucoformin"],
    displayName: "Metformina",
    activeIngredient: "Metformina",
    medicationClass: "Antidiabético",
    defaultAction: "Suspender",
    timing: "Conduta conservadora ADA 2026: omitir no dia do procedimento.",
    restart: "Reiniciar quando houver alimentação, estabilidade hemodinâmica e função renal adequada.",
    adjustments: "Alguns procedimentos menores permitem manutenção se função renal normal, sem contraste e sem risco de hipoperfusão; seguir protocolo local.",
    source: SOURCE,
    suspendDays: 0,
  },
  {
    key: "sglt2",
    names: ["dapagliflozina", "forxiga", "empagliflozina", "jardiance", "canagliflozina", "invokana"],
    displayName: "Inibidor de SGLT2",
    activeIngredient: "Dapagliflozina / empagliflozina / canagliflozina",
    medicationClass: "Antidiabético SGLT2",
    defaultAction: "Suspender",
    timing: "Suspender 3 dias antes.",
    restart: "Somente quando estiver comendo, hidratado, clinicamente estável e sem cetose.",
    adjustments: "Ertugliflozina exige 4 dias. Avaliar cetonas/ânion gap se náusea, acidose ou mal-estar mesmo com glicemia normal.",
    source: SOURCE,
    suspendDays: 3,
  },
  {
    key: "ertugliflozina",
    names: ["ertugliflozina", "steglatro"],
    displayName: "Ertugliflozina",
    activeIngredient: "Ertugliflozina",
    medicationClass: "Antidiabético SGLT2",
    defaultAction: "Suspender",
    timing: "Suspender 4 dias antes.",
    restart: "Somente quando estiver comendo, hidratado, clinicamente estável e sem cetose.",
    adjustments: "Avaliar cetonas/ânion gap se sintomas compatíveis.",
    source: SOURCE,
    suspendDays: 4,
  },
  {
    key: "glp1",
    names: ["semaglutida", "ozempic", "wegovy", "rybelsus", "liraglutida", "victoza", "saxenda", "dulaglutida", "trulicity", "tirzepatida", "mounjaro"],
    displayName: "Agonista GLP-1 / GIP-GLP-1",
    activeIngredient: "Semaglutida / liraglutida / dulaglutida / tirzepatida",
    medicationClass: "GLP-1 / GIP-GLP-1",
    defaultAction: "Individualizar",
    timing: "Baixo risco: manter. Alto risco: dieta apenas líquida por 24 h e considerar ultrassom gástrico, precaução de estômago cheio ou adiamento.",
    restart: "Se houver interrupção, retomar conforme tolerância, alimentação e plano do prescritor.",
    adjustments: "Alto risco: escalonamento, dose elevada, náusea, vômitos, dor, constipação, gastroparesia ou outra condição de esvaziamento lento.",
    source: SOURCE,
  },
  {
    key: "insulina_basal",
    names: ["glargina", "lantus", "toujeo", "detemir", "levemir", "degludeca", "tresiba"],
    displayName: "Insulina basal longa",
    activeIngredient: "Glargina / detemir / degludeca",
    medicationClass: "Insulina",
    defaultAction: "Individualizar",
    timing: "Em geral, usar 75–80% da dose habitual na noite anterior/manhã; reduzir até 50% se alto risco de hipoglicemia.",
    restart: "Ajustar conforme glicemia, alimentação e esquema habitual.",
    adjustments: "Diabetes tipo 1 nunca deve ficar sem insulina basal. Individualizar por DRC, hipoglicemias e duração da cirurgia.",
    source: SOURCE,
  },
  {
    key: "litio",
    names: ["lítio", "litio", "carbolitium"],
    displayName: "Lítio",
    activeIngredient: "Carbonato de lítio",
    medicationClass: "Estabilizador do humor",
    defaultAction: "Suspender",
    timing: "Suspender 72 h antes de cirurgia de maior porte, grandes perdas volêmicas ou risco renal.",
    restart: "Quando hemodinamicamente estável, função renal e eletrólitos normais e alimentação retomada.",
    adjustments: "Procedimento menor pode ser individualizado.",
    source: SOURCE,
    suspendDays: 3,
  },
  {
    key: "fentermina",
    names: ["fentermina", "fórmula para emagrecer", "formula para emagrecer"],
    displayName: "Fentermina / estimulante para emagrecimento",
    activeIngredient: "Fentermina",
    medicationClass: "Psicoestimulante",
    defaultAction: "Suspender",
    timing: "Suspender 4–7 dias antes.",
    restart: "Retomar somente após estabilidade e orientação do prescritor.",
    adjustments: "Investigar estimulantes não declarados em fórmulas manipuladas.",
    source: SOURCE,
    suspendDays: 7,
  },
  {
    key: "fitoterapicos",
    names: ["alho", "arnica", "boldo", "chá de boldo", "cha de boldo", "cúrcuma", "curcuma", "gengibre", "ginkgo", "erva-de-são-joão", "erva de sao joao", "vitamina e"],
    displayName: "Fitoterápico com risco perioperatório",
    activeIngredient: "Fitoterápico / suplemento",
    medicationClass: "Fitoterápico",
    defaultAction: "Suspender",
    timing: "Suspender 2 semanas antes.",
    restart: "Retomar após hemostasia e liberação médica.",
    adjustments: "Confirmar composição real e misturas com estimulantes, vitamina E ou anticoagulantes.",
    source: SOURCE,
    suspendDays: 14,
  },
  {
    key: "levotiroxina",
    names: ["levotiroxina", "puran", "synthroid"],
    displayName: "Levotiroxina",
    activeIngredient: "Levotiroxina",
    medicationClass: "Hormônio tireoidiano",
    defaultAction: "Manter",
    timing: "Manter.",
    restart: "Manter ou retomar assim que possível.",
    adjustments: "Cirurgia eletiva deve aguardar tireotoxicose descontrolada.",
    source: SOURCE,
  },
  {
    key: "inaladores",
    names: ["salbutamol", "aerolin", "formoterol", "budesonida", "symbicort", "seretide", "tiotrópio", "tiotropio", "montelucaste"],
    displayName: "Broncodilatador / corticoide inalado",
    activeIngredient: "Terapia inalatória respiratória",
    medicationClass: "Respiratório",
    defaultAction: "Manter",
    timing: "Manter e usar a dose habitual na manhã da cirurgia.",
    restart: "Manter sem interrupção.",
    adjustments: "Levar inalador ao hospital e tratar exacerbação antes de cirurgia eletiva.",
    source: SOURCE,
  },
  {
    key: "anticonvulsivante",
    names: ["carbamazepina", "tegretol", "fenitoína", "fenitoina", "hidantal", "valproato", "depakene", "lamotrigina", "levetiracetam", "keppra"],
    displayName: "Anticonvulsivante",
    activeIngredient: "Anticonvulsivante",
    medicationClass: "Neurológico",
    defaultAction: "Manter",
    timing: "Manter sem falhas; planejar alternativa IV/enteral se jejum prolongado.",
    restart: "Manter continuamente.",
    adjustments: "Carbamazepina/fenitoína induzem enzimas; valproato pode alterar plaquetas e coagulação.",
    source: SOURCE,
  },
  {
    key: "antidepressivo",
    names: ["sertralina", "fluoxetina", "escitalopram", "citalopram", "paroxetina", "venlafaxina", "desvenlafaxina", "duloxetina"],
    displayName: "ISRS / IRSN",
    activeIngredient: "Antidepressivo",
    medicationClass: "Psicofármaco",
    defaultAction: "Manter",
    timing: "Manter.",
    restart: "Manter sem interrupção.",
    adjustments: "Atenção a hiponatremia, sangramento e síndrome serotoninérgica; evitar interações desnecessárias.",
    source: SOURCE,
  },
  {
    key: "corticoide",
    names: ["prednisona", "prednisolona", "dexametasona", "hidrocortisona", "deflazacorte"],
    displayName: "Corticoide sistêmico crônico",
    activeIngredient: "Corticoide",
    medicationClass: "Corticoide sistêmico",
    defaultAction: "Manter",
    timing: "Manter a dose basal.",
    restart: "Manter; garantir via alternativa se necessário.",
    adjustments: "Avaliar suplementação conforme supressão do eixo HPA e estresse cirúrgico; controlar glicemia.",
    source: SOURCE,
  },
  {
    key: "opioide",
    names: ["morfina", "oxicodona", "tramadol", "fentanil transdérmico", "metadona", "buprenorfina"],
    displayName: "Opioide crônico",
    activeIngredient: "Opioide",
    medicationClass: "Analgésico opioide",
    defaultAction: "Manter",
    timing: "Manter a dose basal, inclusive na manhã da cirurgia.",
    restart: "Manter continuidade e planejar analgesia adicional.",
    adjustments: "A dose basal não cobre toda a dor cirúrgica. Buprenorfina não deve ser suspensa rotineiramente.",
    source: SOURCE,
  },
  {
    key: "dabigatrana",
    names: ["dabigatrana", "pradaxa"],
    displayName: "Dabigatrana",
    activeIngredient: "Dabigatrana",
    medicationClass: "DOAC (anti-IIa)",
    defaultAction: "Suspender",
    timing: "Depende da função renal: ClCr ≥50 mL/min, 24–48 h antes; ClCr 30–50 mL/min, 48–96 h antes.",
    restart: "Após 24 h em baixo/moderado risco ou 48–72 h em alto risco, com hemostasia segura.",
    adjustments: "Neuroeixo exige intervalo ampliado. Idarucizumabe é o antídoto específico em sangramento grave.",
    source: SOURCE,
    suspendDays: 2,
  },
  {
    key: "edoxabana",
    names: ["edoxabana", "lixiana"],
    displayName: "Edoxabana",
    activeIngredient: "Edoxabana",
    medicationClass: "DOAC (anti-Xa)",
    defaultAction: "Suspender",
    timing: "Função renal preservada: cerca de 24 h antes em baixo/moderado risco ou 48 h em alto risco.",
    restart: "Após 24 h em baixo/moderado risco ou 48–72 h em alto risco, com hemostasia segura.",
    adjustments: "Neuroeixo: dose terapêutica ≥72 h. Ampliar intervalo na disfunção renal.",
    source: SOURCE,
    suspendDays: 2,
  },
  {
    key: "bcc",
    names: ["anlodipino", "amlodipino", "nifedipino", "nifedipina", "diltiazem", "verapamil", "felodipino", "lercanidipino"],
    displayName: "Bloqueador do canal de cálcio",
    activeIngredient: "Anlodipino / diltiazem / verapamil",
    medicationClass: "Anti-hipertensivo",
    defaultAction: "Manter",
    timing: "Manter, inclusive na manhã da cirurgia.",
    restart: "Manter sem interrupção.",
    adjustments: "Atenção a bradicardia e depressão da contratilidade com verapamil e diltiazem.",
    source: SOURCE,
  },
  {
    key: "diuretico_tiazidico",
    names: ["hidroclorotiazida", "clortalidona", "indapamida"],
    displayName: "Diurético tiazídico",
    activeIngredient: "Hidroclorotiazida / clortalidona",
    medicationClass: "Diurético",
    defaultAction: "Suspender",
    timing: "Omitir na manhã da cirurgia.",
    restart: "Reiniciar quando houver estabilidade hemodinâmica e volemia adequada.",
    adjustments: "Checar potássio, sódio e volemia no pré-operatório.",
    source: SOURCE,
    suspendDays: 0,
  },
  {
    key: "furosemida",
    names: ["furosemida", "lasix"],
    displayName: "Diurético de alça",
    activeIngredient: "Furosemida",
    medicationClass: "Diurético",
    defaultAction: "Individualizar",
    timing: "Em geral omitir na manhã da cirurgia; manter quando a indicação for congestão ou insuficiência cardíaca descompensada.",
    restart: "Reiniciar conforme volemia, função renal e balanço hídrico.",
    adjustments: "Risco de hipovolemia, hipocalemia e hipotensão na indução.",
    source: SOURCE,
    suspendDays: 0,
  },
  {
    key: "espironolactona",
    names: ["espironolactona", "aldactone", "eplerenona"],
    displayName: "Antagonista mineralocorticoide",
    activeIngredient: "Espironolactona / eplerenona",
    medicationClass: "Diurético poupador de potássio",
    defaultAction: "Individualizar",
    timing: "Considerar omitir na manhã da cirurgia quando houver risco de hipercalemia ou disfunção renal.",
    restart: "Reiniciar com função renal e potássio controlados.",
    adjustments: "Dosar potássio antes de cirurgias de grande porte.",
    source: SOURCE,
    suspendDays: 0,
  },
  {
    key: "sacubitril",
    names: ["sacubitril", "entresto"],
    displayName: "Sacubitril/valsartana",
    activeIngredient: "Sacubitril + valsartana",
    medicationClass: "Inibidor da neprilisina + BRA",
    defaultAction: "Suspender",
    timing: "Considerar omitir 24 h antes pelo risco de hipotensão e vasoplegia.",
    restart: "Reiniciar com pressão, volemia e função renal estáveis.",
    adjustments: "Decisão conjunta com a cardiologia em insuficiência cardíaca de difícil controle.",
    source: SOURCE,
    suspendDays: 1,
  },
  {
    key: "estatina",
    names: ["sinvastatina", "atorvastatina", "rosuvastatina", "pravastatina", "ezetimiba", "estatina"],
    displayName: "Estatina",
    activeIngredient: "Estatina",
    medicationClass: "Hipolipemiante",
    defaultAction: "Manter",
    timing: "Manter, inclusive no dia da cirurgia.",
    restart: "Manter sem interrupção; retomar assim que houver via oral.",
    adjustments: "A suspensão perioperatória está associada a pior desfecho cardiovascular.",
    source: SOURCE,
  },
  {
    key: "amiodarona",
    names: ["amiodarona", "ancoron", "sotalol", "propafenona"],
    displayName: "Antiarrítmico",
    activeIngredient: "Amiodarona / sotalol / propafenona",
    medicationClass: "Antiarrítmico",
    defaultAction: "Manter",
    timing: "Manter a dose habitual.",
    restart: "Manter sem interrupção.",
    adjustments: "Atenção a bradicardia, prolongamento de QT e interações. Amiodarona tem meia-vida muito longa.",
    source: SOURCE,
  },
  {
    key: "digoxina",
    names: ["digoxina", "digoxine"],
    displayName: "Digoxina",
    activeIngredient: "Digoxina",
    medicationClass: "Digitálico",
    defaultAction: "Manter",
    timing: "Manter a dose habitual.",
    restart: "Manter sem interrupção.",
    adjustments: "Janela terapêutica estreita: checar potássio, magnésio e função renal; hipocalemia potencializa toxicidade.",
    source: SOURCE,
  },
  {
    key: "clonidina",
    names: ["clonidina", "atensina", "metildopa"],
    displayName: "Agonista alfa-2 central",
    activeIngredient: "Clonidina / metildopa",
    medicationClass: "Anti-hipertensivo central",
    defaultAction: "Manter",
    timing: "Manter, inclusive no dia da cirurgia.",
    restart: "Manter sem interrupção.",
    adjustments: "A retirada abrupta provoca hipertensão rebote grave.",
    source: SOURCE,
  },
  {
    key: "alfabloqueador",
    names: ["tansulosina", "tamsulosina", "doxazosina", "prazosina", "alfuzosina", "silodosina"],
    displayName: "Alfabloqueador",
    activeIngredient: "Tansulosina / doxazosina",
    medicationClass: "Alfabloqueador",
    defaultAction: "Individualizar",
    timing: "Manter na maioria dos casos; considerar omitir na manhã da cirurgia quando houver risco de hipotensão.",
    restart: "Reiniciar conforme pressão arterial.",
    adjustments: "Informar o oftalmologista antes de cirurgia de catarata pelo risco de síndrome da íris flácida.",
    source: SOURCE,
  },
  {
    key: "ibp",
    names: ["omeprazol", "pantoprazol", "esomeprazol", "lansoprazol", "rabeprazol"],
    displayName: "Inibidor de bomba de prótons",
    activeIngredient: "Omeprazol / pantoprazol",
    medicationClass: "Antissecretor gástrico",
    defaultAction: "Manter",
    timing: "Manter; pode ser usado na manhã da cirurgia com pequeno gole de água.",
    restart: "Manter sem interrupção.",
    adjustments: "Útil em doença do refluxo e risco de broncoaspiração.",
    source: SOURCE,
  },
  {
    key: "sulfonilureia",
    names: ["glibenclamida", "gliclazida", "glimepirida", "glipizida", "daonil", "diamicron", "amaryl"],
    displayName: "Sulfonilureia",
    activeIngredient: "Glibenclamida / gliclazida / glimepirida",
    medicationClass: "Antidiabético",
    defaultAction: "Suspender",
    timing: "Omitir na manhã da cirurgia e enquanto durar o jejum.",
    restart: "Reiniciar quando a alimentação for retomada.",
    adjustments: "Alto risco de hipoglicemia em jejum; monitorar glicemia capilar.",
    source: SOURCE,
    suspendDays: 0,
  },
  {
    key: "dpp4",
    names: ["sitagliptina", "linagliptina", "vildagliptina", "saxagliptina", "januvia", "galvus", "trayenta"],
    displayName: "Inibidor de DPP-4",
    activeIngredient: "Sitagliptina / linagliptina / vildagliptina",
    medicationClass: "Antidiabético",
    defaultAction: "Manter",
    timing: "Pode ser mantido; alternativamente omitir no dia por não haver benefício em jejum.",
    restart: "Reiniciar com a alimentação.",
    adjustments: "Baixo risco de hipoglicemia isoladamente.",
    source: SOURCE,
  },
  {
    key: "insulina_prandial",
    names: ["insulina regular", "insulina rápida", "insulina rapida", "lispro", "humalog", "asparte", "novorapid", "glulisina", "apidra", "insulina nph", "nph"],
    displayName: "Insulina prandial / NPH",
    activeIngredient: "Insulina regular, análogos rápidos e NPH",
    medicationClass: "Insulina",
    defaultAction: "Individualizar",
    timing: "Omitir a insulina prandial durante o jejum. NPH: em geral metade da dose habitual na manhã da cirurgia.",
    restart: "Reiniciar o esquema habitual com a retomada da alimentação.",
    adjustments: "Diabetes tipo 1 nunca deve ficar sem insulina. Monitorar glicemia capilar no perioperatório.",
    source: SOURCE,
  },
  {
    key: "aine",
    names: ["ibuprofeno", "diclofenaco", "naproxeno", "nimesulida", "cetoprofeno", "piroxicam", "aine", "anti-inflamatório"],
    displayName: "Anti-inflamatório não esteroidal",
    activeIngredient: "AINE não seletivo",
    medicationClass: "Anti-inflamatório",
    defaultAction: "Suspender",
    timing: "Suspender cerca de 3 dias antes; piroxicam exige intervalo maior pela meia-vida longa.",
    restart: "Reiniciar após hemostasia adequada e conforme função renal.",
    adjustments: "Risco de sangramento, lesão renal e interação com anticoagulantes. Neuroeixo exige avaliação individual.",
    source: SOURCE,
    suspendDays: 3,
  },
  {
    key: "coxibe",
    names: ["celecoxibe", "etoricoxibe", "arcoxia", "celebra", "parecoxibe"],
    displayName: "Inibidor seletivo de COX-2",
    activeIngredient: "Celecoxibe / etoricoxibe",
    medicationClass: "Anti-inflamatório",
    defaultAction: "Individualizar",
    timing: "Pode ser mantido quando o efeito antiplaquetário for indesejado, por não alterar função plaquetária.",
    restart: "Conforme plano de analgesia.",
    adjustments: "Cautela em doença cardiovascular estabelecida e disfunção renal.",
    source: SOURCE,
  },
  {
    key: "benzodiazepinico",
    names: ["clonazepam", "rivotril", "alprazolam", "frontal", "diazepam", "lorazepam", "bromazepam", "zolpidem"],
    displayName: "Benzodiazepínico / hipnótico",
    activeIngredient: "Benzodiazepínico",
    medicationClass: "Psicofármaco",
    defaultAction: "Manter",
    timing: "Manter; a retirada abrupta causa abstinência.",
    restart: "Manter sem interrupção.",
    adjustments: "Uso crônico aumenta tolerância a sedativos e risco de depressão respiratória combinada a opioides.",
    source: SOURCE,
  },
  {
    key: "antipsicotico",
    names: ["quetiapina", "risperidona", "olanzapina", "haloperidol", "aripiprazol", "clozapina", "clorpromazina"],
    displayName: "Antipsicótico",
    activeIngredient: "Antipsicótico típico ou atípico",
    medicationClass: "Psicofármaco",
    defaultAction: "Manter",
    timing: "Manter para evitar descompensação psiquiátrica.",
    restart: "Manter sem interrupção.",
    adjustments: "Atenção a prolongamento de QT, hipotensão e síndrome neuroléptica maligna. Clozapina exige controle hematológico.",
    source: SOURCE,
  },
  {
    key: "tricíclico",
    names: ["amitriptilina", "nortriptilina", "imipramina", "clomipramina"],
    displayName: "Antidepressivo tricíclico",
    activeIngredient: "Antidepressivo tricíclico",
    medicationClass: "Psicofármaco",
    defaultAction: "Manter",
    timing: "Manter; a suspensão abrupta causa sintomas de retirada.",
    restart: "Manter sem interrupção.",
    adjustments: "Efeitos anticolinérgicos, arritmias e interação com simpaticomiméticos e anestésicos locais com vasoconstritor.",
    source: SOURCE,
  },
  {
    key: "imao",
    names: ["tranilcipromina", "fenelzina", "selegilina", "moclobemida", "imao"],
    displayName: "Inibidor da monoaminoxidase (IMAO)",
    activeIngredient: "IMAO",
    medicationClass: "Psicofármaco",
    defaultAction: "Individualizar",
    timing: "Decisão conjunta com a psiquiatria. Quando a suspensão for aceita, costuma exigir cerca de 2 semanas.",
    restart: "Reiniciar conforme orientação do psiquiatra.",
    adjustments: "Evitar meperidina, efedrina e simpaticomiméticos indiretos pelo risco de crise hipertensiva e síndrome serotoninérgica.",
    source: SOURCE,
    suspendDays: 14,
  },
  {
    key: "levodopa",
    names: ["levodopa", "carbidopa", "prolopa", "sinemet", "pramipexol", "entacapona"],
    displayName: "Antiparkinsoniano",
    activeIngredient: "Levodopa / agonista dopaminérgico",
    medicationClass: "Neurológico",
    defaultAction: "Manter",
    timing: "Manter rigorosamente nos horários, inclusive na manhã da cirurgia.",
    restart: "Retomar o mais cedo possível; planejar via enteral se jejum prolongado.",
    adjustments: "Poucas horas sem a medicação já pioram rigidez e deglutição. Evitar metoclopramida, droperidol e haloperidol.",
    source: SOURCE,
  },
  {
    key: "piridostigmina",
    names: ["piridostigmina", "mestinon"],
    displayName: "Piridostigmina (miastenia gravis)",
    activeIngredient: "Piridostigmina",
    medicationClass: "Anticolinesterásico",
    defaultAction: "Individualizar",
    timing: "Decidir com o neurologista; manter em geral, ponderando a dose da manhã conforme a técnica anestésica.",
    restart: "Retomar assim que possível no pós-operatório.",
    adjustments: "Altera intensamente a resposta a bloqueadores neuromusculares — titular com monitorização de TOF.",
    source: SOURCE,
  },
  {
    key: "metotrexato",
    names: ["metotrexato", "leflunomida", "azatioprina", "micofenolato", "ciclosporina", "tacrolimo"],
    displayName: "Imunossupressor / DMARD sintético",
    activeIngredient: "Metotrexato e imunossupressores",
    medicationClass: "Imunossupressor",
    defaultAction: "Individualizar",
    timing: "Metotrexato costuma ser mantido em cirurgias eletivas com função renal normal; demais imunossupressores seguem orientação do especialista.",
    restart: "Conforme cicatrização, ausência de infecção e orientação do prescritor.",
    adjustments: "Ponderar risco de infecção e má cicatrização contra risco de reativação da doença.",
    source: SOURCE,
  },
  {
    key: "imunobiologico",
    names: ["adalimumabe", "humira", "infliximabe", "etanercepte", "tocilizumabe", "rituximabe", "secuquinumabe", "ustequinumabe"],
    displayName: "Imunobiológico",
    activeIngredient: "Agente biológico",
    medicationClass: "Imunobiológico",
    defaultAction: "Suspender",
    timing: "Programar a cirurgia para o fim do intervalo de dose; a suspensão segue o intervalo de administração de cada agente.",
    restart: "Em geral após cerca de 14 dias, com ferida cicatrizada e sem infecção.",
    adjustments: "Decisão conjunta com reumatologia/gastroenterologia conforme atividade da doença.",
    source: SOURCE,
  },
  {
    key: "contraceptivo",
    names: ["anticoncepcional", "etinilestradiol", "estradiol", "terapia hormonal", "tibolona", "ciproterona"],
    displayName: "Estrogênio / contraceptivo hormonal",
    activeIngredient: "Estrogênio",
    medicationClass: "Hormônio",
    defaultAction: "Individualizar",
    timing: "Em cirurgia de alto risco tromboembólico, considerar suspender cerca de 4 semanas antes.",
    restart: "Reiniciar após deambulação plena e liberação médica.",
    adjustments: "Avaliar risco de gravidez não planejada ao suspender e a necessidade de profilaxia de TEV.",
    source: SOURCE,
    suspendDays: 28,
  },
  {
    key: "tamoxifeno",
    names: ["tamoxifeno", "raloxifeno", "anastrozol"],
    displayName: "Modulador do receptor de estrogênio",
    activeIngredient: "Tamoxifeno / raloxifeno",
    medicationClass: "Hormonioterapia",
    defaultAction: "Individualizar",
    timing: "Em cirurgia de alto risco tromboembólico, considerar suspender de 2 a 4 semanas antes, alinhado à oncologia.",
    restart: "Reiniciar após deambulação e liberação do oncologista.",
    adjustments: "Não interromper tratamento oncológico sem decisão compartilhada.",
    source: SOURCE,
    suspendDays: 14,
  },
  {
    key: "sildenafila",
    names: ["sildenafila", "viagra", "tadalafila", "cialis", "vardenafila"],
    displayName: "Inibidor da fosfodiesterase-5",
    activeIngredient: "Sildenafila / tadalafila",
    medicationClass: "Vasodilatador",
    defaultAction: "Suspender",
    timing: "Suspender 24 h antes (tadalafila, 48 h) quando o uso for para disfunção erétil.",
    restart: "Retomar após estabilidade hemodinâmica.",
    adjustments: "Não suspender quando a indicação for hipertensão pulmonar. Risco de hipotensão grave com nitratos.",
    source: SOURCE,
    suspendDays: 1,
  },
  {
    key: "cilostazol",
    names: ["cilostazol", "pentoxifilina", "dipiridamol"],
    displayName: "Antiagregante / vasoativo periférico",
    activeIngredient: "Cilostazol / dipiridamol",
    medicationClass: "Antiagregante plaquetário",
    defaultAction: "Suspender",
    timing: "Suspender cerca de 5 dias antes; dipiridamol, cerca de 2 dias.",
    restart: "Reiniciar após hemostasia adequada.",
    adjustments: "Para neuroeixo, respeitar o intervalo integral.",
    source: SOURCE,
    suspendDays: 5,
  },
  {
    key: "canabidiol",
    names: ["canabidiol", "cbd", "cannabis medicinal", "thc"],
    displayName: "Canabidiol / cannabis medicinal",
    activeIngredient: "Canabinoides",
    medicationClass: "Canabinoide",
    defaultAction: "Individualizar",
    timing: "Registrar dose, via e horário do último uso; considerar suspender nas 72 h que antecedem a cirurgia.",
    restart: "Retomar conforme orientação do prescritor.",
    adjustments: "Uso crônico aumenta a necessidade de anestésicos e o risco de hiperreatividade de via aérea; interage com anticoagulantes.",
    source: SOURCE,
    suspendDays: 3,
  },
  {
    key: "naltrexona",
    names: ["naltrexona", "revia"],
    displayName: "Naltrexona",
    activeIngredient: "Naltrexona",
    medicationClass: "Antagonista opioide",
    defaultAction: "Suspender",
    timing: "Formulação oral: suspender 72 h antes. Implante ou injetável de longa duração: planejar com muita antecedência.",
    restart: "Reiniciar somente após o término da analgesia com opioides.",
    adjustments: "Bloqueia a analgesia opioide e exige plano analgésico multimodal alternativo.",
    source: SOURCE,
    suspendDays: 3,
  },
  {
    key: "omega3",
    names: ["ômega 3", "omega 3", "óleo de peixe", "oleo de peixe", "suplemento", "multivitamínico", "multivitaminico", "vitamina"],
    displayName: "Suplemento / vitamina",
    activeIngredient: "Suplemento alimentar",
    medicationClass: "Suplemento",
    defaultAction: "Suspender",
    timing: "Suspender cerca de 7 dias antes.",
    restart: "Retomar após liberação médica.",
    adjustments: "Ômega-3 e vitamina E em dose alta prolongam o tempo de sangramento. Confirmar a composição real do produto.",
    source: SOURCE,
    suspendDays: 7,
  },
];

const normalize = (value: string) =>
  value
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, " ")
    .trim();

const escapeRegExp = (value: string) => value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");

// Casa apenas no in\u00edcio de uma palavra, de modo que "AAS 100 mg" reconhe\u00e7a AAS
// sem que termos curtos como "bra" ou "ieca" acertem palavras n\u00e3o relacionadas.
function matchedTermLength(haystack: string, term: string) {
  const normalizedTerm = normalize(term);
  if (!normalizedTerm) return 0;
  const pattern = new RegExp(`(^| )${escapeRegExp(normalizedTerm)}`);
  return pattern.test(haystack) ? normalizedTerm.length : 0;
}

/**
 * Reconhece o medicamento digitado pelo anestesiologista. Quando mais de uma
 * entrada casa (por exemplo "insulina" e "insulina glargina"), vence a
 * correspond\u00eancia mais espec\u00edfica \u2014 a de termo mais longo.
 */
export function findMedicationGuideEntry(name: string) {
  const normalized = normalize(name);
  if (!normalized) return undefined;
  let best: MedicationGuideEntry | undefined;
  let bestLength = 0;
  for (const entry of MEDICATION_GUIDE) {
    for (const candidate of entry.names) {
      const length = matchedTermLength(normalized, candidate);
      if (length > bestLength) {
        best = entry;
        bestLength = length;
      }
    }
  }
  return best;
}

export function calculateLastDoseDate(surgeryDate: string, suspendDays?: number) {
  if (!surgeryDate || suspendDays === undefined) return "";
  const date = new Date(`${surgeryDate}T12:00:00`);
  if (Number.isNaN(date.getTime())) return "";
  date.setDate(date.getDate() - suspendDays);
  return date.toISOString().slice(0, 10);
}

/**
 * As classes que respondem "usa anticoagulante ou antiagregante?".
 *
 * A pergunta da anamnese deixou de ter lista de remédio própria: quem digita
 * Xarelto no item de medicamentos não deve ter que digitar Xarelto de novo
 * três telas depois. A resposta passa a sair daqui, da classe que o próprio
 * guia já atribuiu ao fármaco.
 *
 * A lista é de classes e não de nomes de propósito — cadastrar um antiagregante
 * novo no guia já o faz aparecer na anamnese, sem ninguém lembrar de mexer aqui.
 */
export const CLASSES_ANTITROMBOTICAS = new Set([
  "Antiagregante plaquetário",
  "Antiagregante P2Y12",
  "Antagonista da vitamina K",
  "DOAC (anti-Xa)",
  "DOAC (anti-IIa)",
  "HBPM",
]);

export function ehAntitrombotico(nome: string) {
  const classe = findMedicationGuideEntry(nome)?.medicationClass;
  return classe !== undefined && CLASSES_ANTITROMBOTICAS.has(classe);
}
