export type MedicationGuideEntry = {
  key: string;
  names: string[];
  displayName: string;
  activeIngredient: string;
  medicationClass: string;
  defaultAction: "Manter" | "Suspender" | "Individualizar";
  timing: string;
  restart: string;
  adjustments: string;
  source: string;
  suspendDays?: number;
};

const SOURCE =
  "Guia Perioperatório de Medicamentos, versão 1.0, revisão 07/2026 — SAESP 2025; Miller 7ª ed.; AHA/ACC 2024; ADA 2026; CHEST 2022; ASRA 5ª ed. 2025";

export const MEDICATION_GUIDE: MedicationGuideEntry[] = [
  {
    key: "losartana",
    names: ["losartana", "valsartana", "candesartana", "olmesartana", "telmisartana", "irbesartana", "bra"],
    displayName: "BRA (ex.: losartana)",
    activeIngredient: "Bloqueador do receptor de angiotensina",
    medicationClass: "BRA / anti-hipertensivo",
    defaultAction: "Individualizar",
    timing: "Se usado apenas para hipertensão e a cirurgia tiver risco elevado, considerar omitir cerca de 24 h antes. Em HFrEF estável, pode ser razoável manter.",
    restart: "Reiniciar assim que pressão, volemia e função renal estiverem estáveis.",
    adjustments: "Decidir conforme indicação, PA, volemia, função renal, sangramento previsto e risco de vasoplegia.",
    source: SOURCE,
  },
  {
    key: "ieca",
    names: ["enalapril", "captopril", "ramipril", "lisinopril", "perindopril", "benazepril", "ieca"],
    displayName: "IECA",
    activeIngredient: "Inibidor da enzima conversora de angiotensina",
    medicationClass: "IECA / anti-hipertensivo",
    defaultAction: "Individualizar",
    timing: "Mesma lógica dos BRA: considerar omitir cerca de 24 h antes quando usado para hipertensão em cirurgia de risco elevado.",
    restart: "Reiniciar assim que pressão, volemia e função renal estiverem estáveis.",
    adjustments: "Em insuficiência cardíaca com fração reduzida, ponderar manutenção.",
    source: SOURCE,
  },
  {
    key: "betabloqueador",
    names: ["metoprolol", "atenolol", "carvedilol", "bisoprolol", "propranolol", "nebivolol"],
    displayName: "Betabloqueador",
    activeIngredient: "Betabloqueador",
    medicationClass: "Cardiovascular",
    defaultAction: "Manter",
    timing: "Manter a dose habitual, inclusive no dia da cirurgia.",
    restart: "Manter sem interrupção; retomar assim que possível se a via oral for suspensa.",
    adjustments: "Reduzir ou omitir somente diante de bradicardia grave, choque, bloqueio avançado ou decisão cardiológica.",
    source: SOURCE,
  },
  {
    key: "aas",
    names: ["aas", "aspirina", "ácido acetilsalicílico", "acido acetilsalicilico"],
    displayName: "AAS",
    activeIngredient: "Ácido acetilsalicílico",
    medicationClass: "Antiagregante plaquetário",
    defaultAction: "Individualizar",
    timing: "A decisão depende da indicação. Em stent coronariano, manter sempre que possível. Na prevenção primária, considerar suspender 4–7 dias quando o risco hemorrágico não for trivial.",
    restart: "Manter ou reiniciar nas primeiras 24 h quando a hemostasia permitir.",
    adjustments: "Não decidir isoladamente em PCI/stent recente; considerar risco de sangramento catastrófico.",
    source: SOURCE,
  },
  {
    key: "clopidogrel",
    names: ["clopidogrel", "plavix", "iscover"],
    displayName: "Clopidogrel",
    activeIngredient: "Clopidogrel",
    medicationClass: "Antiagregante P2Y12",
    defaultAction: "Suspender",
    timing: "Quando a interrupção for aceita, suspender 5–7 dias antes.",
    restart: "Reiniciar o mais cedo possível após controle do sangramento; discutir dose de ataque com cardiologia quando indicada.",
    adjustments: "Não suspender automaticamente em stent recente. Para neuroeixo, respeitar 5–7 dias.",
    source: SOURCE,
    suspendDays: 7,
  },
  {
    key: "ticagrelor",
    names: ["ticagrelor", "brilinta"],
    displayName: "Ticagrelor",
    activeIngredient: "Ticagrelor",
    medicationClass: "Antiagregante P2Y12",
    defaultAction: "Suspender",
    timing: "Quando a interrupção for aceita, suspender 3–5 dias antes; para neuroeixo, usar 5 dias.",
    restart: "Reiniciar o mais cedo possível após controle do sangramento.",
    adjustments: "Não suspender automaticamente em stent recente.",
    source: SOURCE,
    suspendDays: 5,
  },
  {
    key: "prasugrel",
    names: ["prasugrel", "effient"],
    displayName: "Prasugrel",
    activeIngredient: "Prasugrel",
    medicationClass: "Antiagregante P2Y12",
    defaultAction: "Suspender",
    timing: "Quando a interrupção for aceita, suspender 7–10 dias antes.",
    restart: "Reiniciar o mais cedo possível após controle do sangramento.",
    adjustments: "Não suspender automaticamente em stent recente; neuroeixo exige 7–10 dias.",
    source: SOURCE,
    suspendDays: 10,
  },
  {
    key: "rivaroxabana",
    names: ["rivaroxabana", "xarelto"],
    displayName: "Rivaroxabana",
    activeIngredient: "Rivaroxabana",
    medicationClass: "DOAC (anti-Xa)",
    defaultAction: "Suspender",
    timing: "Função renal preservada: cerca de 24 h antes em baixo/moderado risco hemorrágico ou 48 h em alto risco.",
    restart: "Em geral, após cerca de 24 h em baixo/moderado risco ou 48–72 h em alto risco, somente com hemostasia segura.",
    adjustments: "Neuroeixo: dose terapêutica ≥72 h. Aumentar intervalo em insuficiência renal, baixo peso, interações ou sangramento catastrófico. Não fazer ponte rotineira.",
    source: SOURCE,
    suspendDays: 2,
  },
  {
    key: "apixabana",
    names: ["apixabana", "eliquis"],
    displayName: "Apixabana",
    activeIngredient: "Apixabana",
    medicationClass: "DOAC (anti-Xa)",
    defaultAction: "Suspender",
    timing: "Função renal preservada: cerca de 24 h antes em baixo/moderado risco hemorrágico ou 48 h em alto risco.",
    restart: "Em geral, após cerca de 24 h em baixo/moderado risco ou 48–72 h em alto risco, somente com hemostasia segura.",
    adjustments: "Neuroeixo: dose terapêutica ≥72 h. Individualizar por função renal, dose, peso e risco hemorrágico.",
    source: SOURCE,
    suspendDays: 2,
  },
  {
    key: "varfarina",
    names: ["varfarina", "marevan", "coumadin"],
    displayName: "Varfarina",
    activeIngredient: "Varfarina",
    medicationClass: "Antagonista da vitamina K",
    defaultAction: "Suspender",
    timing: "Suspender 5 dias antes e verificar INR próximo ao procedimento.",
    restart: "Em geral 12–24 h após, quando a via oral for possível e houver hemostasia.",
    adjustments: "Ponte não é rotina; reservar para risco tromboembólico muito alto. Neuroeixo exige INR normalizado.",
    source: SOURCE,
    suspendDays: 5,
  },
  {
    key: "enoxaparina",
    names: ["enoxaparina", "clexane", "versa"],
    displayName: "Enoxaparina",
    activeIngredient: "Enoxaparina",
    medicationClass: "HBPM",
    defaultAction: "Suspender",
    timing: "Dose profilática: última dose ≥12 h antes. Dose terapêutica: ≥24 h antes.",
    restart: "Individualizar pela hemostasia; após cirurgia de alto risco, dose terapêutica costuma aguardar 48–72 h.",
    adjustments: "Considerar intervalo maior na disfunção renal. Neuroeixo segue regras específicas de dose e cateter.",
    source: SOURCE,
    suspendDays: 1,
  },
  {
    key: "metformina",
    names: ["metformina", "glifage", "glucoformin"],
    displayName: "Metformina",
    activeIngredient: "Metformina",
    medicationClass: "Antidiabético",
    defaultAction: "Suspender",
    timing: "Conduta conservadora ADA 2026: omitir no dia do procedimento.",
    restart: "Reiniciar quando houver alimentação, estabilidade hemodinâmica e função renal adequada.",
    adjustments: "Alguns procedimentos menores permitem manutenção se função renal normal, sem contraste e sem risco de hipoperfusão; seguir protocolo local.",
    source: SOURCE,
    suspendDays: 0,
  },
  {
    key: "sglt2",
    names: ["dapagliflozina", "forxiga", "empagliflozina", "jardiance", "canagliflozina", "invokana"],
    displayName: "Inibidor de SGLT2",
    activeIngredient: "Dapagliflozina / empagliflozina / canagliflozina",
    medicationClass: "Antidiabético SGLT2",
    defaultAction: "Suspender",
    timing: "Suspender 3 dias antes.",
    restart: "Somente quando estiver comendo, hidratado, clinicamente estável e sem cetose.",
    adjustments: "Ertugliflozina exige 4 dias. Avaliar cetonas/ânion gap se náusea, acidose ou mal-estar mesmo com glicemia normal.",
    source: SOURCE,
    suspendDays: 3,
  },
  {
    key: "ertugliflozina",
    names: ["ertugliflozina", "steglatro"],
    displayName: "Ertugliflozina",
    activeIngredient: "Ertugliflozina",
    medicationClass: "Antidiabético SGLT2",
    defaultAction: "Suspender",
    timing: "Suspender 4 dias antes.",
    restart: "Somente quando estiver comendo, hidratado, clinicamente estável e sem cetose.",
    adjustments: "Avaliar cetonas/ânion gap se sintomas compatíveis.",
    source: SOURCE,
    suspendDays: 4,
  },
  {
    key: "glp1",
    names: ["semaglutida", "ozempic", "wegovy", "rybelsus", "liraglutida", "victoza", "saxenda", "dulaglutida", "trulicity", "tirzepatida", "mounjaro"],
    displayName: "Agonista GLP-1 / GIP-GLP-1",
    activeIngredient: "Semaglutida / liraglutida / dulaglutida / tirzepatida",
    medicationClass: "GLP-1 / GIP-GLP-1",
    defaultAction: "Individualizar",
    timing: "Baixo risco: manter. Alto risco: dieta apenas líquida por 24 h e considerar ultrassom gástrico, precaução de estômago cheio ou adiamento.",
    restart: "Se houver interrupção, retomar conforme tolerância, alimentação e plano do prescritor.",
    adjustments: "Alto risco: escalonamento, dose elevada, náusea, vômitos, dor, constipação, gastroparesia ou outra condição de esvaziamento lento.",
    source: SOURCE,
  },
  {
    key: "insulina_basal",
    names: ["glargina", "lantus", "toujeo", "detemir", "levemir", "degludeca", "tresiba"],
    displayName: "Insulina basal longa",
    activeIngredient: "Glargina / detemir / degludeca",
    medicationClass: "Insulina",
    defaultAction: "Individualizar",
    timing: "Em geral, usar 75–80% da dose habitual na noite anterior/manhã; reduzir até 50% se alto risco de hipoglicemia.",
    restart: "Ajustar conforme glicemia, alimentação e esquema habitual.",
    adjustments: "Diabetes tipo 1 nunca deve ficar sem insulina basal. Individualizar por DRC, hipoglicemias e duração da cirurgia.",
    source: SOURCE,
  },
  {
    key: "litio",
    names: ["lítio", "litio", "carbolitium"],
    displayName: "Lítio",
    activeIngredient: "Carbonato de lítio",
    medicationClass: "Estabilizador do humor",
    defaultAction: "Suspender",
    timing: "Suspender 72 h antes de cirurgia de maior porte, grandes perdas volêmicas ou risco renal.",
    restart: "Quando hemodinamicamente estável, função renal e eletrólitos normais e alimentação retomada.",
    adjustments: "Procedimento menor pode ser individualizado.",
    source: SOURCE,
    suspendDays: 3,
  },
  {
    key: "fentermina",
    names: ["fentermina", "fórmula para emagrecer", "formula para emagrecer"],
    displayName: "Fentermina / estimulante para emagrecimento",
    activeIngredient: "Fentermina",
    medicationClass: "Psicoestimulante",
    defaultAction: "Suspender",
    timing: "Suspender 4–7 dias antes.",
    restart: "Retomar somente após estabilidade e orientação do prescritor.",
    adjustments: "Investigar estimulantes não declarados em fórmulas manipuladas.",
    source: SOURCE,
    suspendDays: 7,
  },
  {
    key: "fitoterapicos",
    names: ["alho", "arnica", "boldo", "chá de boldo", "cha de boldo", "cúrcuma", "curcuma", "gengibre", "ginkgo", "erva-de-são-joão", "erva de sao joao", "vitamina e"],
    displayName: "Fitoterápico com risco perioperatório",
    activeIngredient: "Fitoterápico / suplemento",
    medicationClass: "Fitoterápico",
    defaultAction: "Suspender",
    timing: "Suspender 2 semanas antes.",
    restart: "Retomar após hemostasia e liberação médica.",
    adjustments: "Confirmar composição real e misturas com estimulantes, vitamina E ou anticoagulantes.",
    source: SOURCE,
    suspendDays: 14,
  },
  {
    key: "levotiroxina",
    names: ["levotiroxina", "puran", "synthroid"],
    displayName: "Levotiroxina",
    activeIngredient: "Levotiroxina",
    medicationClass: "Hormônio tireoidiano",
    defaultAction: "Manter",
    timing: "Manter.",
    restart: "Manter ou retomar assim que possível.",
    adjustments: "Cirurgia eletiva deve aguardar tireotoxicose descontrolada.",
    source: SOURCE,
  },
  {
    key: "inaladores",
    names: ["salbutamol", "aerolin", "formoterol", "budesonida", "symbicort", "seretide", "tiotrópio", "tiotropio", "montelucaste"],
    displayName: "Broncodilatador / corticoide inalado",
    activeIngredient: "Terapia inalatória respiratória",
    medicationClass: "Respiratório",
    defaultAction: "Manter",
    timing: "Manter e usar a dose habitual na manhã da cirurgia.",
    restart: "Manter sem interrupção.",
    adjustments: "Levar inalador ao hospital e tratar exacerbação antes de cirurgia eletiva.",
    source: SOURCE,
  },
  {
    key: "anticonvulsivante",
    names: ["carbamazepina", "tegretol", "fenitoína", "fenitoina", "hidantal", "valproato", "depakene", "lamotrigina", "levetiracetam", "keppra"],
    displayName: "Anticonvulsivante",
    activeIngredient: "Anticonvulsivante",
    medicationClass: "Neurológico",
    defaultAction: "Manter",
    timing: "Manter sem falhas; planejar alternativa IV/enteral se jejum prolongado.",
    restart: "Manter continuamente.",
    adjustments: "Carbamazepina/fenitoína induzem enzimas; valproato pode alterar plaquetas e coagulação.",
    source: SOURCE,
  },
  {
    key: "antidepressivo",
    names: ["sertralina", "fluoxetina", "escitalopram", "citalopram", "paroxetina", "venlafaxina", "desvenlafaxina", "duloxetina"],
    displayName: "ISRS / IRSN",
    activeIngredient: "Antidepressivo",
    medicationClass: "Psicofármaco",
    defaultAction: "Manter",
    timing: "Manter.",
    restart: "Manter sem interrupção.",
    adjustments: "Atenção a hiponatremia, sangramento e síndrome serotoninérgica; evitar interações desnecessárias.",
    source: SOURCE,
  },
  {
    key: "corticoide",
    names: ["prednisona", "prednisolona", "dexametasona", "hidrocortisona", "deflazacorte"],
    displayName: "Corticoide sistêmico crônico",
    activeIngredient: "Corticoide",
    medicationClass: "Corticoide sistêmico",
    defaultAction: "Manter",
    timing: "Manter a dose basal.",
    restart: "Manter; garantir via alternativa se necessário.",
    adjustments: "Avaliar suplementação conforme supressão do eixo HPA e estresse cirúrgico; controlar glicemia.",
    source: SOURCE,
  },
  {
    key: "opioide",
    names: ["morfina", "oxicodona", "tramadol", "fentanil transdérmico", "metadona", "buprenorfina"],
    displayName: "Opioide crônico",
    activeIngredient: "Opioide",
    medicationClass: "Analgésico opioide",
    defaultAction: "Manter",
    timing: "Manter a dose basal, inclusive na manhã da cirurgia.",
    restart: "Manter continuidade e planejar analgesia adicional.",
    adjustments: "A dose basal não cobre toda a dor cirúrgica. Buprenorfina não deve ser suspensa rotineiramente.",
    source: SOURCE,
  },
];

const normalize = (value: string) =>
  value.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase().trim();

export function findMedicationGuideEntry(name: string) {
  const normalized = normalize(name);
  return MEDICATION_GUIDE.find((entry) =>
    entry.names.some((candidate) => normalized.includes(normalize(candidate))),
  );
}

export function calculateLastDoseDate(surgeryDate: string, suspendDays?: number) {
  if (!surgeryDate || suspendDays === undefined) return "";
  const date = new Date(`${surgeryDate}T12:00:00`);
  if (Number.isNaN(date.getTime())) return "";
  date.setDate(date.getDate() - suspendDays);
  return date.toISOString().slice(0, 10);
}
